---

- name: Set workon home path
  become: yes
  action:
    module: lineinfile
    dest: "{{ virtualenvwrapper_shell_file }}"
    line: "export WORKON_HOME={{ virtualenvwrapper_home }}"
    insertbefore: "BOF"
    state: present
    backup: yes
    create: yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper.configuration

- name: Set project path
  become: yes
  action:
    module: lineinfile
    dest: "{{ virtualenvwrapper_shell_file }}"
    line: "export PROJECT_HOME={{ virtualenvwrapper_project }}"
    insertafter: "export WORKON_HOME={{ virtualenvwrapper_home }}"
    state: present
    backup: yes
    create: yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper.configuration

- name: Set virtualenvwrapper python path
  become: yes
  action:
    module: lineinfile
    dest: "{{ virtualenvwrapper_shell_file }}"
    line: "export VIRTUALENVWRAPPER_PYTHON={{ virtualenvwrapper_python }}"
    insertafter: "export PROJECT_HOME={{ virtualenvwrapper_project }}"
    state: present
    backup: yes
    create: yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper.configuration

- name: Set virtualenvwrapper path
  become: yes
  action:
    module: lineinfile
    dest: "{{ virtualenvwrapper_shell_file }}"
    line: "export VIRTUALENVWRAPPER_VIRTUALENV={{ virtualenvwrapper_virtualenv }}"
    insertafter: "export VIRTUALENVWRAPPER_PYTHON={{ virtualenvwrapper_python }}"
    state: present
    backup: yes
    create: yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper.configuration

- name: Load virtualenvwrapper.sh
  become: yes
  action:
    module: lineinfile
    dest: "{{ virtualenvwrapper_shell_file }}"
    line: "source {{ virtualenvwrapper_source }}"
    insertafter: "export VIRTUALENVWRAPPER_VIRTUALENV={{ virtualenvwrapper_virtualenv }}"
    state: present
    backup: yes
    create: yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper.configurationa
